In [90]:
import numpy as np
import pandas as pd
df = pd.read_csv('Housing Price data set.csv')
df.head()

Unnamed: 0    price  lotsize  bedrooms  bathrms  stories driveway recroom  \
0           1  42000.0     5850         3        1        2      yes      no   
1           2  38500.0     4000         2        1        1      yes      no   
2           3  49500.0     3060         3        1        1      yes      no   
3           4  60500.0     6650         3        1        2      yes     yes   
4           5  61000.0     6360         2        1        1      yes      no   

  fullbase gashw airco  garagepl prefarea  
0      yes    no    no         1       no  
1       no    no    no         0       no  
2       no    no    no         0       no  
3       no    no    no         0       no  
4       no    no    no         0       no

In [91]:
temp={'yes':1,'no':0}
df.driveway=[temp[i] for i in df.driveway]
df.recroom=[temp[i] for i in df.recroom]
df.fullbase=[temp[i] for i in df.fullbase]
df.gashw=[temp[i] for i in df.gashw]
df.airco=[temp[i] for i in df.airco]
df.prefarea=[temp[i] for i in df.prefarea]
df.head()

Unnamed: 0    price  lotsize  bedrooms  bathrms  stories  driveway  \
0           1  42000.0     5850         3        1        2         1   
1           2  38500.0     4000         2        1        1         1   
2           3  49500.0     3060         3        1        1         1   
3           4  60500.0     6650         3        1        2         1   
4           5  61000.0     6360         2        1        1         1   

   recroom  fullbase  gashw  airco  garagepl  prefarea  
0        0         1      0      0         1         0  
1        0         0      0      0         0         0  
2        0         0      0      0         0         0  
3        1         0      0      0         0         0  
4        0         0      0      0         0         0

In [92]:
tempy = df[['price']].values
tempx = df[['lotsize','bedrooms','bathrms','stories','driveway','recroom','fullbase','gashw','airco','garagepl','prefarea']].values
print(X)

[[5850 3 1 ... 0 1 0]
 [4000 2 1 ... 0 0 0]
 [3060 3 1 ... 0 0 0]
 ...
 [6000 3 2 ... 1 1 0]
 [6000 3 2 ... 1 1 0]
 [6000 3 1 ... 1 1 0]]


In [89]:

one=np.ones(size,dtype=int)
matx=np.insert(tempx,0,one,axis=1)
print(matx[0])
transpose_x=np.transpose(matx)
temp=np.matmul(transpose_x,matx)
temp2=np.matmul(transpose_x,tempy)
invtemp=np.linalg.inv(temp)
#print(invtemp)
parameters=np.matmul(invtemp,temp2)
print(parameters)

[   1 5850    3    1    2    1    0    1    0    0    1    0]
[[-4.03835043e+03]
 [ 3.54630297e+00]
 [ 1.83200347e+03]
 [ 1.43355585e+04]
 [ 6.55694571e+03]
 [ 6.68777889e+03]
 [ 4.51128383e+03]
 [ 5.45238554e+03]
 [ 1.28314063e+04]
 [ 1.26328904e+04]
 [ 4.24482900e+03]
 [ 9.36951324e+03]]
